"""
Django settings for book_store project.

Generated by 'django-admin startproject' using Django 5.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

import dj_database_url

from django.core.exceptions import ImproperlyConfigured

from django.conf.global_settings import STATICFILES_DIRS, MEDIA_URL, STORAGES, SESSION_COOKIE_HTTPONLY, \
    SESSION_COOKIE_SAMESITE, CSRF_COOKIE_SAMESITE, SECURE_CONTENT_TYPE_NOSNIFF, X_FRAME_OPTIONS, \
    SECURE_PROXY_SSL_HEADER, SECURE_HSTS_INCLUDE_SUBDOMAINS, CSRF_TRUSTED_ORIGINS, INTERNAL_IPS

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

def env_bool(name, default=False):
    value = os.getenv(name)

    if value is None:
        return default

    return value.lower() in {
        "1",
        "true",
        "yes",
        "on"
    }

def env_list(name, default=""):
    value = os.getenv(name, default)

    return [
        item.strip()
        for item in value.split(",")
        if item.strip()
    ]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DEBUG', default=True)

SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-development-key",
)



# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = env_bool('SECRET_KEY')
#
# if not SECRET_KEY:
#     if DEBUG:
#         SECRET_KEY = 'django-insecure-8i*h2xa6dvn9agao$v^qm(3#*k86rz!cj@l#i^or8z6@#%nq+o'
#     else:
#         raise ImproperlyConfigured(
#             'у продакшині потрібно встановити секретний ключ'
#         )

ALLOWED_HOSTS = env_list(
    'ALLOWED_HOSTS',
    '127.0.0.1, localhost'
)

CSRF_TRUSTED_ORIGINS = env_list(
    'CSRF_TRUSTED_ORIGINS',
    'http://127.0.0.1:8000,http://localhost:8000'
)

railway_domain = os.getenv('RAILWAY_PUBLIC_DOMAIN')

if railway_domain:
    if railway_domain not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(railway_domain)

    railway_origin = f'http://{railway_domain}'

    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users.apps.UsersConfig',
    'store.apps.StoreConfig',
    'cart',
    'orders.apps.OrdersConfig',
    'checkout',
    'review',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    MIDDLEWARE.insert(
        1,
        'debug_toolbar.middleware.DebugToolbarMiddleware',
    )

    INTERNAL_IPS = [
        '127.0.0.1',
    ]

ROOT_URLCONF = 'book_store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',
                'store.context_processors.recently_viewed_products',
            ],
        },
    },
]

WSGI_APPLICATION = 'book_store.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import os
import dj_database_url

DATABASES = {
    "default": dj_database_url.config(
        default="sqlite:///db.sqlite3",
        conn_max_age=600,
    )
}

REDIS_URL = os.getenv('REDIS_URL')

if REDIS_URL:
    CASHES = {
        'default' : {
            'BACKEND' : 'django.core.cache.backends.redis.RedisCache',
            'LOCATION' : REDIS_URL,
            'TIMEOUT' : 300,
            'KEY_PREFIX' : 'online_shop',
        },
    }
else:
    CASHES = {
        'default' : {
            'BACKEND' : 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION' : 'online_shop_development',
             'TIMEOUT' : 300
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

STATIC_ROOT = BASE_DIR / 'staticfiles'



MEDIA_ROOT = BASE_DIR / 'media'




STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
    if DEBUG
    else 'whitenoise.storage.WhiteNoiseFilesStorage',
    },
}

SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE = 'Lax'
CSRF_COOKIE_SAMESITE = 'Lax'

SECURE_CONTENT_TYPE_NOSNIFF = True
X_FRAME_OPTIONS = 'DENY'

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = (
        'HTTP_X_FORWARDED_PROTO',
        'https',
    )

    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HITS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HITS_PRELOAD = False

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'users.CustomUser'

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
FAULT_FROM_EMAIL = 'Book Store <noreply@boostrore.com>'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'your_email@gmail.com'
EMAIL_HOST_PASSWORD = 'app-password'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

INTERNAL_IPS = [
    "127.0.0.1",
]