# Generated by Django 6.0.7 on 2026-07-29 22:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Знижка, %')),
                ('valid_from', models.DateTimeField(verbose_name='Діє з')),
                ('valid_to', models.DateTimeField(verbose_name='Діє до')),
                ('max_uses', models.PositiveIntegerField(default=1, verbose_name='Максимальна кількість використань')),
                ('used_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Кількість використань')),
                ('active', models.BooleanField(default=True, verbose_name='Активний')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Оплата карткою'), ('cash', 'Оплата готівкою (при отриманні)')], default='card', max_length=20, verbose_name='Спосіб оплати'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.coupon', verbose_name='Промокод'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('processing', 'Обробляється'), ('shipped', 'Відправлено'), ('delivered', 'Доставлено'), ('cancelled', 'Скасовано')], max_length=20, verbose_name='статус')),
                ('comment', models.TextField(blank=True, verbose_name='коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата зміни')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='хто змінив')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='замовлення')),
            ],
            options={
                'verbose_name': 'Історія статусу',
                'verbose_name_plural': 'Історія статусів',
                'ordering': ['-created_at'],
            },
        ),
    ]
